### ISSUE TITLE
SQL Server installation issue

### ISSUE THREAD

**Issue by MELLENS** [learn-chef/awesome_customers_windows#7]
Installing using AzureRM driver.  Get an error during SQL server install.  Any ideas how to debug?

Thanks

Mark
                  Error executing action `install` on resource 'windows_package[Microsoft SQL Server 2012 (64-bit)]'
           ================================================================================

```
       Mixlib::ShellOut::ShellCommandFailed
       ------------------------------------
       Expected process to exit with [0, 42, 127], but received '-2068578304'
       ---- Begin output of start "" /wait "c:\users\azure\appdata\local\temp\kitchen\cache\package\sqlexpr_x64_enu.exe"   /q /ConfigurationFile=C:\Users\azure\AppData\Local\Temp\kitchen\cache\ConfigurationFile.ini  & exit %%%%ERRORLEVEL%%%% ----
       STDOUT:
       STDERR:
       ---- End output of start "" /wait "c:\users\azure\appdata\local\temp\kitchen\cache\package\sqlexpr_x64_enu.exe"   /q /ConfigurationFile=C:\Users\azure\AppData\Local\Temp\kitchen\cache\ConfigurationFile.ini  & exit %%%%ERRORLEVEL%%%% ----
       Ran start "" /wait "c:\users\azure\appdata\local\temp\kitchen\cache\package\sqlexpr_x64_enu.exe"   /q /ConfigurationFile=C:\Users\azure\AppData\Local\Temp\kitchen\cache\ConfigurationFile.ini  & exit %%%%ERRORLEVEL%%%% returned -2068578304
```

**Comment by donbecker** [comment]
@MELLENS  try running this from your powershell window on the workstation: 
PS> kitchen exec -c "cat 'C:\Program Files\Microsoft SQL Server\110\Setup Bootstrap\Log\Summary.txt'"

It will print the install log.

**Comment by tpetchel** [comment]
Hi @MELLENS,

I'm guessing you ran into this issue.

https://learn.chef.io/manage-a-web-app/windows/run-your-web-application-on-a-node/#comment-3004289913

Let us know if setting that node attribute fixes things for you.

I plan on updating the tutorial to handle the Azure case. Sorry for the inconvenience!

**Comment by tpetchel** [comment]
Just realized this issue is months old, so I'm closing it. Sorry I didn't notice it earlier; I typically look for user comments on the Learn Chef site. Again, apologies.

**Comment by mcascone** [comment]
> https://learn.chef.io/manage-a-web-app/windows/run-your-web-application-on-a-node/#comment-3004289913

this link is dead... can anyone share what the fix is?

edit... I think there are two commonly-accepted takeaways here:
1. set `elevated: true` in the `transport` section of `.kitchen.yml`
    1. I haven't personally seen an improvement from this, but I don't think I'm yet at the point in the process where it would have an effect.
2. inspect `C:\Program Files\Microsoft SQL Server\<some number>\Setup Bootstrap\Log\Summary.txt` for error messages. They're actually incredibly clear.
